version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: src/TimetableService/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=timetable.db
    volumes:
      - ./src/TimetableService:/app
    depends_on:
      - db
  db:
    image: alpine:latest
    command: sh -c "apk add --no-cache sqlite && sqlite3 /data/timetable.db 'CREATE TABLE IF NOT EXISTS Groups (Id INTEGER PRIMARY KEY, Name TEXT);'"
    volumes:
      - ./data:/data 